name: PHP
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    with:
      php-version: '8.2'
      extensions: zlib
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: Test
        run: |
          make ci-tests